version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: fastapi-database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-local:
    image: postgres:15-alpine
    container_name: fastapi-database-local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}_local
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}_local
      - POSTGRES_DB=${POSTGRES_DB}_local
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER}_local -d ${POSTGRES_DB}_local",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fastapi-app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
