"""add inactive field into user

Revision ID: 369f135ad448
Revises: 8d6fdfb99ba6
Create Date: 2025-10-31 17:42:31.818007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369f135ad448'
down_revision: Union[str, Sequence[str], None] = '8d6fdfb99ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inactive', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'inactive')
    # ### end Alembic commands ###
